'use client';
import {useState,useEffect} from 'react';
import {LayoutDashboard,Dumbbell,Play,Image as ImageIcon,MessageSquare,TrendingUp,UserRound,Wallet,Inbox,Users,Plus,ArrowUpRight,Pencil,Trash2,ChevronUp,ChevronDown,Menu,Check} from 'lucide-react';
import {toast,Toaster} from 'sonner';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {useApex} from '@/lib/apex/store';
import {createId,images,money,programSeed} from '@/lib/apex/data';
import type {Program,Lesson,Review,Result,Media,Coach,State} from '@/lib/apex/models';
import {Logo,Btn,Eyebrow,Title,SectionHead,Photo,Panel,Empty} from './ui';
const sections=[{id:'overview',title:'Обзор',icon:LayoutDashboard},{id:'programs',title:'Программы',icon:Dumbbell},{id:'lessons',title:'Уроки и видео',icon:Play},{id:'media',title:'Медиа',icon:ImageIcon},{id:'reviews',title:'Отзывы',icon:MessageSquare},{id:'results',title:'Результаты',icon:TrendingUp},{id:'coach',title:'Профиль тренера',icon:UserRound},{id:'prices',title:'Цены и тарифы',icon:Wallet},{id:'applications',title:'Заявки',icon:Inbox},{id:'users',title:'Пользователи',icon:Users}];
type Kind='programs'|'lessons'|'reviews'|'results'|'media';
type Entity=Program|Lesson|Review|Result|Media;
type Edit={kind:Kind;item:Entity;isNew:boolean};
const uid=()=>createId();
function values(f:FormData){return {str:(k:string)=>String(f.get(k)||'').trim(),num:(k:string)=>Number(f.get(k))};}
export default function AdminApp(){const {state:s,update,ready,storageError}=useApex();const [section,setSection]=useState('overview');const [selectedProgram,setSelectedProgram]=useState('mass');const [edit,setEdit]=useState<Edit|null>(null);const [remove,setRemove]=useState<{kind:Kind;id:string}|null>(null);const [mediaError,setMediaError]=useState('');useEffect(()=>{if(!s.programs.some(p=>p.id===selectedProgram))setSelectedProgram(s.programs[0]?.id||'')},[s.programs,selectedProgram]);
 const openNew=(kind:Kind)=>{const defaults:Record<Kind,Entity>={programs:{...programSeed[0],id:uid(),name:'Новая программа',tag:'НОВАЯ ЦЕЛЬ',slogan:'Твой следующий шаг.',description:'',status:'draft'},lessons:{id:uid(),programId:selectedProgram,title:'',description:'',duration:10,thumbnail:images.strength,videoUrl:'',status:'draft',order:s.lessons.filter(l=>l.programId===selectedProgram).length},reviews:{id:uid(),name:'',program:s.programs.find(p=>p.id===selectedProgram)?.name||'APEX',text:'',rating:5,period:'1 месяц',photo:''},results:{id:uid(),name:'',before:70,after:75,months:3,goal:'Набор мышечной массы',photo:images.strength},media:{id:uid(),name:'',url:''}};setEdit({kind,item:defaults[kind],isNew:true})};
 const save=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!edit)return;const f=new FormData(event.currentTarget),{str,num}=values(f);let item:Entity=edit.item;
 if(edit.kind==='programs')item={...(edit.item as Program),name:str('name'),tag:str('tag'),slogan:str('slogan'),description:str('description'),audience:str('audience'),goal:str('goal'),format:str('format'),price:num('price'),weeks:num('weeks'),sessions:num('sessions'),cover:str('cover')||images.strength,status:str('status') as Program['status'],benefits:str('benefits').split('\n').filter(Boolean),phases:str('phases').split('\n').filter(Boolean),days:str('days').split(',').map(Number).filter((d,i,a)=>d>=0&&d<=6&&Number.isInteger(d)&&a.indexOf(d)===i)};
 if(edit.kind==='lessons')item={...(edit.item as Lesson),programId:selectedProgram,title:str('title'),description:str('description'),duration:num('duration'),thumbnail:str('thumbnail')||images.strength,videoUrl:str('videoUrl'),status:str('status') as Lesson['status'],order:num('order')};
 if(edit.kind==='reviews')item={...(edit.item as Review),name:str('name'),program:str('program'),text:str('text'),rating:num('rating'),period:str('period'),photo:str('photo')};
 if(edit.kind==='results')item={...(edit.item as Result),name:str('name'),before:num('before'),after:num('after'),months:num('months'),goal:str('goal'),photo:str('photo')||images.strength};
 if(edit.kind==='media')item={...(edit.item as Media),name:str('name'),url:str('url')};
 const urlKeys=['cover','thumbnail','photo','videoUrl','url'];for(const key of urlKeys){const value=(item as unknown as Record<string,unknown>)[key];if(value&&typeof value==='string'&&!safeUrl(value)){toast.error('Укажи HTTPS-ссылку или локальный путь к медиа.');return}}
 if(edit.kind==='programs'&&!(item as Program).days.length){toast.error('Укажи хотя бы один тренировочный день (0–6).');return}
 update(state=>({...state,[edit.kind]:edit.isNew?[...state[edit.kind],item]:state[edit.kind].map(x=>x.id===item.id?item:x)}));toast.success('Сохранено. Изменения уже видны в приложении.');setEdit(null)};
 const deleteItem=()=>{if(!remove)return;update(state=>{const next={...state,[remove.kind]:state[remove.kind].filter(x=>x.id!==remove.id)};if(remove.kind==='programs'){next.lessons=state.lessons.filter(l=>l.programId!==remove.id);if(next.activeProgram===remove.id)next.activeProgram=''}return next});setRemove(null);toast.success('Удалено')};
 const changeOrder=(lesson:Lesson,direction:number)=>{const list=s.lessons.filter(l=>l.programId===selectedProgram).sort((a,b)=>a.order-b.order);const i=list.findIndex(l=>l.id===lesson.id),other=list[i+direction];if(!other)return;[list[i],list[i+direction]]=[list[i+direction],list[i]];update(s=>({...s,lessons:s.lessons.map(l=>l.programId===selectedProgram?{...l,order:list.findIndex(x=>x.id===l.id)}:l)}));toast.success('Порядок уроков обновлён')};
 const upload=async(file:File|undefined)=>{if(!file)return;setMediaError('');if(!file.type.startsWith('image/')||file.size>1_500_000){setMediaError('Выбери изображение PNG, JPG или WebP размером до 1,5 МБ.');return}const reader=new FileReader();reader.onload=()=>{update(s=>({...s,media:[...s.media,{id:uid(),name:file.name,url:String(reader.result)}]}));toast.success('Изображение добавлено в демо-медиатеку')};reader.onerror=()=>setMediaError('Не удалось прочитать файл.');reader.readAsDataURL(file)};
 const actions=(kind:Kind,item:Entity)=><div className="row-actions"><button aria-label={`Редактировать ${'name'in item?item.name:'title'in item?item.title:'элемент'}`} onClick={()=>setEdit({kind,item,isNew:false})}><Pencil size={17}/></button><button aria-label="Удалить" onClick={()=>setRemove({kind,id:item.id})}><Trash2 size={17}/></button></div>;
 const programSelect=<label className="program-picker">Программа<select value={selectedProgram} onChange={e=>setSelectedProgram(e.target.value)}>{s.programs.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>;
 if(!ready)return <div className="loading"><Logo/><span>Открываем кабинет тренера…</span></div>;
 return <SidebarProvider><Toaster theme="dark" richColors position="top-center"/><Sidebar className="admin-sidebar"><SidebarHeader><a href="/" className="admin-logo"><Logo/></a><Eyebrow>COACH STUDIO</Eyebrow></SidebarHeader><SidebarContent><SidebarMenu>{sections.map(({id,title,icon:Icon})=><SidebarMenuItem key={id}><SidebarMenuButton isActive={section===id} onClick={()=>setSection(id)}><Icon/><span>{title}</span>{id==='applications'&&<b>{s.applications.length}</b>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><a href="/" className="admin-client-link">Клиентское приложение<ArrowUpRight size={16}/></a><span className="fine">DEMO CMS · БЕЗ АВТОРИЗАЦИИ</span></SidebarFooter></Sidebar><main className="admin-main"><header className="admin-top"><div><SidebarTrigger/><span>APEX / КАБИНЕТ ТРЕНЕРА</span></div><span className="demo-label">DEMO</span></header><div className="admin-content">{storageError&&<p role="alert" className="error-banner">{storageError}</p>}<Title kicker="ВСЁ ПОД ТВОИМ КОНТРОЛЕМ" title={sections.find(x=>x.id===section)?.title||'Обзор'} copy={section==='overview'?`Добро пожаловать, ${s.coach.name}. Твоя платформа в одном месте.`:'Изменения сохраняются в этом браузере и сразу видны в клиентской части.'}/>
 {section==='overview'&&<><div className="metric-grid"><article><span>ПОЛЬЗОВАТЕЛИ · ДЕМО</span><strong>128</strong><p>иллюстративная метрика</p></article><article><span>ОПУБЛИКОВАНО ПРОГРАММ</span><strong>{s.programs.filter(p=>p.status==='published').length}</strong><p>{s.lessons.length} уроков в библиотеке</p></article><article><span>ДЕМО-ПОКУПКИ</span><strong>{money(s.purchases.reduce((a,p)=>a+p.price,0))}</strong><p>{s.purchases.length} локальных покупок</p></article><article><span>ЗАЯВКИ</span><strong>{s.applications.length}</strong><button onClick={()=>setSection('applications')}>Посмотреть<ArrowUpRight size={15}/></button></article></div><div className="admin-overview-grid"><section className="panel-block"><SectionHead title="Быстрый старт"/><div className="admin-quick"><button onClick={()=>{setSection('lessons');openNew('lessons')}}><Play/><strong>Добавить видеоурок</strong><p>Название, обложка и ссылка на видео</p><ArrowUpRight/></button><button onClick={()=>{setSection('programs');openNew('programs')}}><Plus/><strong>Создать программу</strong><p>Новая цель для твоих клиентов</p><ArrowUpRight/></button></div></section><section className="panel-block"><SectionHead title="Активность · демо"/><div className="activity-bars">{[38,52,46,72,59,87,65].map((v,i)=><div key={i}><span>{v}</span><div style={{height:v+'px'}}/><small>{['ПН','ВТ','СР','ЧТ','ПТ','СБ','ВС'][i]}</small></div>)}</div><p className="fine">Вымышленные активные пользователи за неделю</p></section></div><section className="section"><SectionHead title="Последние заявки" action="Все заявки" onClick={()=>setSection('applications')}/><Applications data={s.applications.slice(-3).reverse()}/></section><p className="demo-note">Это демонстрационная панель без защиты паролем. Здесь нет реальных пользователей, платежей или отправки сообщений.</p></>}
 {section==='programs'&&<><div className="admin-toolbar"><span>{s.programs.length} программы</span><Btn onClick={()=>openNew('programs')}><Plus/>Добавить программу</Btn></div><div className="admin-table">{s.programs.map(p=><div className="admin-program-row" key={p.id}><Photo src={p.cover}/><div><h3>{p.name}</h3><p>{p.weeks} нед. · {p.sessions} тренировок</p><span className={`pill ${p.status==='published'?'published':''}`}>{p.status==='published'?'Опубликована':'Черновик'}</span></div><strong>{money(p.price)}</strong><button className="text-link" onClick={()=>{setSelectedProgram(p.id);setSection('lessons')}}>Уроки<Play size={14}/></button>{actions('programs',p)}</div>)}</div></>}
 {section==='lessons'&&<><div className="admin-toolbar">{programSelect}<Btn disabled={!s.programs.length} onClick={()=>openNew('lessons')}><Plus/>Добавить урок</Btn></div><div className="demo-note"><Play size={22}/><p>Чтобы добавить видео: создай урок, укажи название и прямую HTTPS-ссылку на MP4, затем выбери «Опубликован». Без ссылки будет красивая демо-обложка.</p></div><div className="admin-table">{s.lessons.filter(l=>l.programId===selectedProgram).sort((a,b)=>a.order-b.order).map((l,i,arr)=><div className="admin-lesson-row" key={l.id}><span className="muted">{String(i+1).padStart(2,'0')}</span><Photo src={l.thumbnail}/><div><h3>{l.title}</h3><p>{l.duration} мин · {l.videoUrl?'Видео добавлено':'Демо-обложка'} · {l.status==='published'?'Опубликован':'Черновик'}</p></div><div className="order-actions"><button disabled={i===0} aria-label="Переместить вверх" onClick={()=>changeOrder(l,-1)}><ChevronUp size={17}/></button><button disabled={i===arr.length-1} aria-label="Переместить вниз" onClick={()=>changeOrder(l,1)}><ChevronDown size={17}/></button></div>{actions('lessons',l)}</div>)}</div></>}
 {section==='media'&&<><div className="admin-toolbar"><label className="upload-button"><Plus size={18}/>Добавить фото<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(e.target.files?.[0])}/></label><Btn secondary onClick={()=>openNew('media')}>Добавить по ссылке<Plus/></Btn></div><p className="fine">Фото до 1,5 МБ сохраняются локально. «Скопировать ссылку» позволяет вставить изображение в обложку программы или урока.</p>{mediaError&&<p className="error-banner">{mediaError}</p>}<div className="media-grid">{s.media.map(m=><article key={m.id}><Photo src={m.url} alt={m.name}/><div><h3>{m.name}</h3>{actions('media',m)}</div><button className="text-link" onClick={async()=>{try{await navigator.clipboard.writeText(m.url);toast.success('Ссылка скопирована')}catch{toast.error('Браузер не разрешил копирование. Открой редактирование и скопируй ссылку вручную.')}}}>Скопировать ссылку<ArrowUpRight size={15}/></button></article>)}</div></>}
 {section==='reviews'&&<><div className="admin-toolbar"><p className="muted">Все отзывы вымышлены</p><Btn onClick={()=>openNew('reviews')}><Plus/>Добавить отзыв</Btn></div><div className="admin-review-grid">{s.reviews.map(r=><article className="panel-block" key={r.id}><div className="admin-review-heading"><h3>{r.name}</h3>{actions('reviews',r)}</div><span className="stars">{'★'.repeat(r.rating)}</span><p>{r.text}</p><small>{r.program} · {r.period}</small></article>)}</div></>}
 {section==='results'&&<><div className="admin-toolbar"><p className="muted">Демонстрационные истории</p><Btn onClick={()=>openNew('results')}><Plus/>Добавить результат</Btn></div><div className="admin-review-grid">{s.results.map(r=><article className="panel-block" key={r.id}><Photo src={r.photo} className="result-admin-photo"/><div className="admin-review-heading"><h3>{r.name}</h3>{actions('results',r)}</div><h2>{r.before} → {r.after} кг</h2><p>{r.goal} · {r.months} месяцев</p></article>)}</div></>}
 {section==='coach'&&<form className="coach-form panel-block" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),{str,num}=values(f);if(!safeUrl(str('photo'))){toast.error('Укажи корректную ссылку на фото');return}update(s=>({...s,coach:{name:str('name'),bio:str('bio'),experience:num('experience'),specialty:str('specialty'),photo:str('photo'),contact:str('contact')}}));toast.success('Профиль тренера обновлён')}}><Photo src={s.coach.photo} className="coach-admin-photo"/><div className="form-grid"><Field name="name" label="Имя тренера" value={s.coach.name}/><Field name="specialty" label="Специализация" value={s.coach.specialty}/><Field name="experience" label="Опыт, лет" value={s.coach.experience} type="number" min={0} max={60}/><Field name="contact" label="Контакт для связи" value={s.coach.contact}/></div><TextField name="bio" label="О тренере" value={s.coach.bio}/><MediaField name="photo" label="Фото тренера" value={s.coach.photo} media={s.media}/><Btn type="submit">Сохранить профиль<Check/></Btn></form>}
 {section==='prices'&&<form className="panel-block price-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);update(s=>({...s,programs:s.programs.map(p=>({...p,price:Number(f.get('p-'+p.id))})),packages:s.packages.map(p=>({...p,price:Number(f.get('c-'+p.id))}))}));toast.success('Все цены обновлены')}}><SectionHead title="Стоимость программ"/>{s.programs.map(p=><Field key={p.id} name={'p-'+p.id} label={`${p.name}, ₽`} value={p.price} type="number" min={0}/>) }<p className="fine">Консультация: +3 000 ₽ к базовой цене. Personal для программы: +9 000 ₽.</p><SectionHead title="Персональное сопровождение"/>{s.packages.map(p=><Field key={p.id} name={'c-'+p.id} label={`${p.name}, ₽`} value={p.price} type="number" min={0}/>)}<Btn type="submit">Сохранить цены<Check/></Btn></form>}
 {section==='applications'&&<><p className="demo-note">Заявки из клиентской формы сохраняются здесь локально. Начальная заявка Анны — пример.</p><Applications data={[...s.applications].reverse()}/>{!s.applications.length&&<p className="muted">Новых заявок пока нет.</p>}</>}
 {section==='users'&&<><p className="demo-note">Вымышленные профили для демонстрации. Настоящая регистрация и серверная аналитика не подключены.</p><div className="admin-table">{[['Александр',s.programs.find(p=>p.id===s.activeProgram)?.name||'Программа не выбрана','Текущий браузер'],['Анна Соколова','HOME 30','Демо-пользователь'],['Денис Орлов','MASS 90','Демо-пользователь'],['Полина Зайцева','LEAN 60','Демо-пользователь']].map(([n,p,status])=><div className="user-row" key={n}><span className="avatar">{n[0]}</span><div><h3>{n}</h3><p>{status}</p></div><span>{p}</span></div>)}</div></>}
 </div></main>
 <Panel open={!!edit} onClose={()=>setEdit(null)} title={edit?`${edit.isNew?'Добавить':'Редактировать'}: ${{programs:'программа',lessons:'урок',reviews:'отзыв',results:'результат',media:'медиа'}[edit.kind]}`:''} description="Сохрани изменения, чтобы показать их в клиентском приложении">{edit&&<form key={edit.item.id} className="admin-edit-form" onSubmit={save}>
 {edit.kind==='programs'&&(()=>{const p=edit.item as Program;return <><div className="form-grid"><Field name="name" label="Название" value={p.name}/><Field name="tag" label="Категория" value={p.tag}/></div><Field name="slogan" label="Слоган" value={p.slogan}/><TextField name="description" label="Описание" value={p.description}/><TextField name="audience" label="Кому подходит" value={p.audience}/><div className="form-grid"><Field name="goal" label="Цель программы" value={p.goal}/><Field name="format" label="Формат" value={p.format}/></div><div className="form-grid"><Field name="price" label="Цена, ₽" value={p.price} type="number" min={0}/><Field name="weeks" label="Продолжительность, недель" value={p.weeks} type="number" min={1} max={52}/><Field name="sessions" label="Количество тренировок" value={p.sessions} type="number" min={1} max={365}/><Field name="days" label="Дни: 0 — пн, 6 — вс (через запятую)" value={p.days.join(',')}/></div><MediaField name="cover" label="Обложка" value={p.cover} media={s.media}/><TextField name="benefits" label="Преимущества, по одному в строке" value={p.benefits.join('\n')}/><TextField name="phases" label="Этапы, по одному в строке" value={p.phases.join('\n')}/><Status value={p.status}/></>})()}
 {edit.kind==='lessons'&&(()=>{const l=edit.item as Lesson;return <><p className="lime">{s.programs.find(p=>p.id===selectedProgram)?.name} → Уроки</p><Field name="title" label="Название урока" value={l.title}/><TextField name="description" label="О чём урок" value={l.description}/><MediaField name="thumbnail" label="Обложка урока" value={l.thumbnail} media={s.media}/><Field name="videoUrl" label="Ссылка на видео (MP4, HTTPS)" value={l.videoUrl} required={false}/><p className="fine">Пустое поле — демо-плеер. Ссылка должна вести на видеофайл, а не на страницу YouTube.</p><div className="form-grid"><Field name="duration" label="Длительность, минут" value={l.duration} type="number" min={1} max={300}/><Field name="order" label="Позиция (от 0)" value={l.order} type="number" min={0}/></div><Status value={l.status}/></>})()}
 {edit.kind==='reviews'&&(()=>{const r=edit.item as Review;return <><Field name="name" label="Имя" value={r.name}/><Field name="program" label="Программа" value={r.program}/><TextField name="text" label="Текст отзыва" value={r.text}/><div className="form-grid"><Field name="rating" label="Оценка от 1 до 5" value={r.rating} type="number" min={1} max={5}/><Field name="period" label="Срок занятий" value={r.period}/></div><MediaField name="photo" label="Фото (можно оставить пустым)" value={r.photo} media={s.media} required={false}/></>})()}
 {edit.kind==='results'&&(()=>{const r=edit.item as Result;return <><Field name="name" label="Имя" value={r.name}/><Field name="goal" label="Цель" value={r.goal}/><div className="form-grid"><Field name="before" label="Вес до, кг" value={r.before} type="number" min={25} step="0.1"/><Field name="after" label="Вес после, кг" value={r.after} type="number" min={25} step="0.1"/><Field name="months" label="Срок, месяцев" value={r.months} type="number" min={1}/></div><MediaField name="photo" label="Фото" value={r.photo} media={s.media}/></>})()}
 {edit.kind==='media'&&(()=>{const m=edit.item as Media;return <><Field name="name" label="Название изображения" value={m.name}/><Field name="url" label="HTTPS-ссылка или локальный путь" value={m.url}/></>})()}
 <Btn type="submit">Сохранить изменения<Check/></Btn></form>}</Panel>
 <AlertDialog open={!!remove} onOpenChange={v=>{if(!v)setRemove(null)}}><AlertDialogContent className="apex-alert"><AlertDialogHeader><AlertDialogTitle>Удалить этот элемент?</AlertDialogTitle><AlertDialogDescription>{remove?.kind==='programs'?'Программа и её уроки исчезнут из каталога. История демо-покупок останется.':'Элемент исчезнет из клиентской части. Восстановить начальные данные можно сбросом демо.'}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Отмена</AlertDialogCancel><AlertDialogAction onClick={deleteItem}>Удалить</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </SidebarProvider>
}
function safeUrl(v:string){return v.startsWith('/images/')||/^data:image\/(png|jpeg|webp);base64,/.test(v)||/^https:\/\//.test(v)}
function Field({label,name,value,required=true,...props}:{label:string;name:string;value:string|number;required?:boolean}&React.ComponentProps<typeof Input>){return <label>{label}<Input name={name} defaultValue={value} required={required} {...props}/></label>}
function TextField({label,name,value}:{label:string;name:string;value:string}){return <label>{label}<Textarea name={name} defaultValue={value} required rows={3}/></label>}
function MediaField({label,name,value,media,required=true}:{label:string;name:string;value:string;media:Media[];required?:boolean}){const [url,setUrl]=useState(value);return <label>{label}<div className="media-input"><Input name={name} value={url} required={required} onChange={e=>setUrl(e.target.value)}/><select value="" onChange={e=>setUrl(e.target.value)} aria-label={`Выбрать ${label.toLowerCase()} из медиатеки`}><option value="">Из медиатеки</option>{media.map(m=><option key={m.id} value={m.url}>{m.name}</option>)}</select></div></label>}
function Status({value}:{value:string}){return <label>Статус<select name="status" defaultValue={value}><option value="draft">Черновик</option><option value="published">Опубликован</option></select></label>}
function Applications({data}:{data:State['applications']}){return <div className="application-list">{data.map(a=><article className="panel-block" key={a.id}><div><span className="pill published">{a.package}</span><small>{new Date(a.date).toLocaleDateString('ru-RU')}</small></div><h3>{a.name}</h3><p>{a.goal}</p><dl><dt>Опыт</dt><dd>{a.experience}</dd><dt>Контакт</dt><dd>{a.contact}</dd></dl></article>)}</div>}
