import type {Exercise, Program, State, Workout} from './models';

export const images={coach:'/images/coach.webp',strength:'/images/strength.webp',mobility:'/images/mobility.webp'};

export const programSeed:Program[]=[
  {id:'mass',name:'MASS 90',tag:'НАБОР МАССЫ',slogan:'Сила, которая меняет тебя.',description:'Системная работа с базовыми движениями и понятная прогрессия. Построй фундамент силы за 12 недель — без случайных тренировок.',audience:'Для тех, кто уже знаком с залом и хочет последовательно набирать мышечную массу.',goal:'Мышечная масса и базовая сила',format:'Зал · силовой сплит',weeks:12,sessions:36,price:3990,cover:images.strength,status:'published',benefits:['3 тренировки в неделю','Техника каждого движения','Дневник нагрузки и прогресса','Восстановление и питание'],phases:['01–04 · Основа и техника','05–08 · Рост рабочего объёма','09–12 · Сила и закрепление'],days:[0,2,4]},
  {id:'lean',name:'LEAN 60',tag:'РЕЛЬЕФ И ТОНУС',slogan:'Легче. Сильнее. Увереннее.',description:'Силовые тренировки, умеренное кардио и устойчивые привычки. Создай форму, которую легко поддерживать.',audience:'Для людей с базовой подготовкой, которые хотят улучшить композицию тела.',goal:'Рельеф и композиция тела',format:'Зал · силовой + кардио',weeks:8,sessions:32,price:4490,cover:images.mobility,status:'published',benefits:['4 занятия в неделю','Силовой и кардио блоки','Контроль интенсивности','Простые привычки питания'],phases:['01–02 · Вход в ритм','03–06 · Основной цикл','07–08 · Закрепление'],days:[0,1,3,5]},
  {id:'home',name:'HOME 30',tag:'ТРЕНИРОВКИ ДОМА',slogan:'Твоё пространство. Твой темп.',description:'30 дней движения без сложного оборудования. Коврик, пара гантелей и полчаса для себя.',audience:'Для начинающих и тех, кто предпочитает заниматься дома.',goal:'Регулярность и тонус',format:'Дома · минимум оборудования',weeks:4,sessions:12,price:2490,cover:images.mobility,status:'published',benefits:['30 минут на тренировку','Минимум оборудования','Доступный уровень','Мобильность всего тела'],phases:['01 · Знакомство с движением','02–03 · Регулярность','04 · Новый уровень'],days:[0,2,4]},
  {id:'athlete',name:'ATHLETE 90',tag:'ФУНКЦИОНАЛЬНАЯ СИЛА',slogan:'Готов к большему.',description:'Сила, выносливость и свобода движения в одном цикле. Подготовка к активной жизни и любимому спорту.',audience:'Для тренирующихся с опытом, которым нужна разносторонняя подготовка.',goal:'Атлетизм и выносливость',format:'Зал · функциональный цикл',weeks:12,sessions:48,price:5990,cover:images.strength,status:'published',benefits:['4 тренировки в неделю','Работа с мощностью','Мобильность и баланс','Развитие выносливости'],phases:['01–04 · Контроль движения','05–08 · Сила и мощность','09–12 · Атлетизм'],days:[0,1,3,5]},
];

const lessonTitles=['Добро пожаловать в APEX','Основы прогрессии нагрузки','Техника жима лёжа','Приседания: движение под контролем','Тяга и здоровая спина','Разминка перед тренировкой','Восстановление без перегрузки','Сон как часть программы','Питание для твоей цели','Как отслеживать прогресс'];

export function initialState():State{
  return {
    version:1,
    programs:programSeed,
    lessons:programSeed.flatMap(p=>lessonTitles.map((title,i)=>({id:`${p.id}-l${i}`,programId:p.id,title,description:i===0?'Познакомься со структурой программы и начни в удобном темпе.':'Разбираем принципы и практические шаги. Сохрани заметки и вернись к уроку перед тренировкой.',duration:6+i,thumbnail:i%3===0?images.coach:i%3===1?images.strength:images.mobility,videoUrl:'',status:'published' as const,order:i}))),
    coach:{name:'Марк Волков',bio:'Я помогаю выстроить систему, в которой результат — следствие привычек. Техника, осознанная нагрузка и восстановление. Без крайностей. С уважением к твоему темпу.',experience:9,specialty:'Силовая подготовка · Композиция тела',photo:images.coach,contact:'Демо-контакт тренера'},
    reviews:[['Алексей','MASS 90','Впервые понимаю, зачем делаю каждое упражнение. План убрал хаос из тренировок.','3 месяца'],['Дарья','LEAN 60','Перестала начинать с понедельника. Небольшие шаги стали частью обычного дня.','2 месяца'],['Михаил','ATHLETE 90','Нравится баланс силы и мобильности. Стал увереннее чувствовать себя на корте.','4 месяца'],['Анна','HOME 30','Полчаса дома оказались удобнее вечных поисков времени на зал.','1 месяц'],['Денис','MASS 90','Понятная последовательность, объяснения и возможность видеть свой прогресс.','3 месяца'],['Полина','LEAN 60','Особенно помогли уроки про восстановление. Теперь меньше гонки и больше регулярности.','2 месяца']].map(([name,program,text,period],i)=>({id:`r${i}`,name,program,text,period,rating:5,photo:''})),
    results:[{id:'t1',name:'Алексей',before:67,after:76,months:6,goal:'Набор мышечной массы',photo:images.strength},{id:'t2',name:'Дарья',before:72,after:65,months:4,goal:'Композиция тела',photo:images.mobility},{id:'t3',name:'Михаил',before:78,after:81,months:5,goal:'Сила и выносливость',photo:images.coach}],
    packages:[{id:'start',name:'START',price:6990,description:'Уверенный первый шаг',features:['Программа под твою цель','Стартовая консультация 45 минут','Рекомендации по технике']},{id:'personal',name:'PERSONAL',price:12990,description:'Система, созданная под тебя',features:['Индивидуальный план','Корректировки каждую неделю','Обратная связь в чате','Разбор техники по видео']},{id:'elite',name:'ELITE',price:24990,description:'Максимум внимания к деталям',features:['Всё из PERSONAL','2 видеосозвона в месяц','Сопровождение по питанию','Приоритетная обратная связь']}],
    applications:[{id:'demo-a1',name:'Анна Соколова',goal:'Вернуться к регулярным тренировкам',experience:'Начинаю',contact:'Демо-пользователь',package:'PERSONAL',date:'2026-09-14'}],
    media:[{id:'m1',name:'Марк · портрет',url:images.coach},{id:'m2',name:'Силовая подготовка',url:images.strength},{id:'m3',name:'Мобильность',url:images.mobility}],
    purchases:[],completed:[],exerciseChecks:{},setLogs:{},workoutStatus:{},workoutHistory:[],lessonChecks:[],habits:{},
    weights:[{date:'2026-08-05',value:70},{date:'2026-08-12',value:70.4},{date:'2026-08-19',value:70.2},{date:'2026-08-26',value:71},{date:'2026-09-02',value:71.3},{date:'2026-09-09',value:71.8}],
    userName:'Александр',reminders:true,activeProgram:'',
  };
}

const exercise=(id:string,name:string,muscle:string,sets:number,reps:string,defaultWeight:string,technique:string,image=images.strength):Exercise=>({id,name,muscle,sets,reps,defaultWeight,rest:90,technique,image});

export const workouts:Workout[]=[
  {id:'push',title:'PUSH A',subtitle:'Грудь / плечи / трицепс',exercises:[exercise('bench','Жим штанги лёжа','Грудь',4,'8','40','Сведи лопатки, держи стопы на полу. Опускай штангу подконтрольно, без отскока.'),exercise('incline','Жим гантелей под наклоном','Верх груди',3,'10','14','Угол скамьи около 30°. Сохраняй устойчивое положение плеч.'),exercise('shoulder','Жим гантелей сидя','Плечи',3,'10','12','Не прогибай поясницу. Поднимай гантели без рывков.'),exercise('lateral','Махи гантелями в стороны','Средняя дельта',4,'12','6','Мягкие локти. Веди движение плечом, не поднимай плечи к ушам.'),exercise('triceps','Разгибание рук на блоке','Трицепс',3,'12','20','Зафиксируй локти рядом с корпусом. Полностью контролируй возврат.')]},
  {id:'pull',title:'PULL A',subtitle:'Спина / задняя дельта / бицепс',exercises:[exercise('pulldown','Тяга верхнего блока','Широчайшие',4,'10','35','Веди локти вниз, не раскачивай корпус.'),exercise('row','Тяга гантели в наклоне','Спина',3,'10','18','Сохраняй нейтральную спину. Тяни локоть к тазу.'),exercise('facepull','Тяга каната к лицу','Задняя дельта',3,'12','15','Разводи локти и сохраняй спокойный темп.'),exercise('curl','Сгибание рук с гантелями','Бицепс',3,'12','8','Не помогай корпусом. Опускай вес медленно.')]},
  {id:'legs',title:'LOWER A',subtitle:'Ноги / ягодицы / корпус',exercises:[exercise('squat','Приседания с гантелью','Квадрицепс / ягодицы',4,'10','20','Колени направлены по линии стоп. Опускайся в комфортной амплитуде.'),exercise('rdl','Румынская тяга','Задняя поверхность бедра',3,'10','35','Отводи таз назад, держи вес близко к ногам.'),exercise('lunge','Обратные выпады','Ноги / ягодицы',3,'12','10','Шагни назад и сохраняй опору на передней стопе.'),exercise('plank','Планка','Корпус',3,'30','—','Дыши спокойно. Удерживай корпус в одной линии.',images.mobility)]},
  {id:'home',title:'FULL BODY',subtitle:'Всё тело / домашняя тренировка',exercises:[exercise('air','Приседания','Ноги',3,'15','0','Опускай таз между стоп, сохраняй устойчивость.',images.mobility),exercise('pushup','Отжимания от опоры','Грудь / трицепс',3,'10','0','Сохраняй корпус прямым. Выбирай удобную высоту опоры.',images.mobility),exercise('bridge','Ягодичный мост','Ягодицы',3,'15','0','Поднимай таз без чрезмерного прогиба поясницы.',images.mobility),exercise('bird','Птица-собака','Корпус',3,'10','0','Вытягивай противоположную руку и ногу без поворота таза.',images.mobility)]},
];

export const habits=[{id:'water',label:'Вода',target:'2 л',icon:'water'},{id:'food',label:'Питание',target:'По плану',icon:'food'},{id:'steps',label:'Движение',target:'8 000 шагов',icon:'steps'},{id:'sleep',label:'Сон',target:'8 часов',icon:'sleep'},{id:'workout',label:'Тренировка',target:'По плану',icon:'workout'}];
export const faq=[['Подойдёт ли мне программа?','Выбери программу по опыту и доступному оборудованию. HOME 30 рассчитана на начинающих, MASS 90 и LEAN 60 — на базовую подготовку, ATHLETE 90 — на опытных.'],['Как долго доступны материалы?','В этой демонстрации материалы доступны до сброса данных в текущем браузере. Условия реальной покупки определяет тренер.'],['Что нужно для занятий?','Для программ в зале — стандартное оборудование. Для HOME 30 — коврик, устойчивая опора и по желанию гантели.'],['Что происходит после покупки?','Демо-покупка сразу открывает план и уроки. Деньги не списываются.'],['Можно ли заменить упражнение?','В персональном сопровождении тренер адаптирует программу. В демо можно оставить заявку и описать свою цель.']];
export const money=(value:number)=>new Intl.NumberFormat('ru-RU').format(value)+' ₽';
export const dayKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
export function streak(s:State){let n=0;const d=new Date();if(!(s.habits[dayKey(d)]?.length))d.setDate(d.getDate()-1);for(let i=0;i<366;i++){if(!s.habits[dayKey(d)]?.length)break;n++;d.setDate(d.getDate()-1)}return n;}
export function workoutFor(program:Program,day:number){return program.id==='home'?workouts[3]:workouts[Math.max(0,program.days.indexOf(day))%3];}
export function planDate(week:number,day:number){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-(d.getDay()+6)%7+week*7+day);return d;}
export function workoutKey(programId:string,week:number,day:number){return `${programId}:${week}:${day}`;}
export const createId=()=>typeof crypto!=='undefined'&&typeof crypto.randomUUID==='function'?crypto.randomUUID():`demo-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,12)}`;
